### ISSUE TITLE
ImportError: cannot import name 'dump'

### ISSUE THREAD

**Issue by aronsoyol** [vaidik/commentjson#17]
~/.pyenv/versions/3.6.0/lib/python3.6/site-packages/commentjson/__init__.py in <module>()
----> 1 from commentjson import dump
      2 from commentjson import dumps
      3 from commentjson import JSONLibraryException
      4 from commentjson import load
      5 from commentjson import loads

ImportError: cannot import name 'dump'

**Comment by vaidik** [comment]
Sorry this has been broken for a while and I haven't had the time to maintain this library. I have just fixed this. The fix is in the master and I am going to release the new version soon
