### ISSUE TITLE
Latest lark-parser isn't compatible with commentjson

### ISSUE THREAD

**Issue by ianfhunter** [vaidik/commentjson#32]
https://pypi.org/project/lark-parser/#history was released 32mins ago.

>     import commentjson as json
>     /home/testuser/.local/lib/python3.6/site-packages/commentjson/__init__.py:1: in <module>
>         from .commentjson import dump
>     /home/testuser/.local/lib/python3.6/site-packages/commentjson/commentjson.py:55: in      <module>
>         serializer = Reconstructor(parser)
>     /home/testuser/.local/lib/python3.6/site-packages/lark/reconstruct.py:92: in __init__
>         assert parser.options.maybe_placeholders == False

**Comment by ianfhunter** [comment]
Current work around - people can use my branch:
pip install git+https://github.com/ianfhunter/commentjson.git@patch-1

I will delete this after merged

**Comment by erezsh** [comment]
Sorry about that! I reverted the change in `0.8.1` (already released), and will use a major version for such a change next time.

**Comment by pkolbus** [comment]
Hi @erezsh, what you did in lark-parser is correct according to SemVer, prior to 1.0.0 anything can change at any time as the API is explicitly unstable. It’s commentjson not constraining the dependency correctly.

That said, thanks for reverting, as that will help until commentjson can fix things.

**Comment by ianfhunter** [comment]
No worries, Thanks for the revert :)

**Comment by vaidik** [comment]
On it folks. Reviewing the PR

**Comment by vaidik** [comment]
Hey guys

I have merged the PRs and cut a release - 0.8.3.

@ianfhunter thanks a lot for the patch! Really appreciate it!
