### ISSUE TITLE
Deprecation warning due to invalid escape sequences in Python 3.8

### ISSUE THREAD

**Issue by tirkarthi** [vaidik/commentjson#36]
Deprecation warnings are raised due to invalid escape sequences in Python 3.8 . Below is a log of the warnings raised during compiling all the python files. Using raw strings or escaping them will fix this issue.

```
find . -iname '*.py'  | xargs -P 4 -I{} python -Walways -m py_compile {}

./commentjson/commentjson.py:32: DeprecationWarning: invalid escape sequence \/
  parser = Lark('''
```

**Comment by vaidik** [comment]
Thanks for reporting this. I have fixed this issue. But I am not making a release just yet because it is only a warning and hopefully there will be a real reason to make a release sooner than Python actually deprecates this.
