### ISSUE TITLE
JSon Array and Hash not working

### ISSUE THREAD

**Issue by lumy** [vaidik/commentjson#4]
Hi,

If you put an Hash in a array Json that raise an exception.

Test 1 Work
{
    "a": ["1","2"],
    "b": 2 # b inline comment
}

Test 2 Don't Work
{
    "a": ["1#","2"],
    "b": 2 # b inline comment
}

**Comment by vaidik** [comment]
Yes correct. As a matter of fact, the existing regex would fail for anything that is not properly formatted. I will try to churn out something that handles this situation. But that's not on priority. Until then, you can split the array into multiple lines and continue to use this - a little verbose but it works.

**Comment by salty-horse** [comment]
You probably need a real "JSON with comments" parser, not a regex.

**Comment by vaidik** [comment]
Sorry for getting around to this so late. I was not maintaining commentjson in between. Got really busy with my day job. I am trying to maintain this now regularly. So expect faster responses.

This is fixed. Now there is a proper parser which addresses all these cases. You can try the latest [version](https://github.com/vaidik/commentjson/releases/tag/v0.8.0) of commentjson which addresses this and a lot of other unhandled cases like this.
