### ISSUE TITLE
commentjson raises the wrong error type on trailing comma

### ISSUE THREAD

**Issue by EliRibble** [vaidik/commentjson#43]
For example, let's say commentjson is told to load the following:

```
{
  // there is a trailing comma below
  "c": 1,
}
```

This will be caught on `commentjson.py:170` as a `lark.exceptions.UnexpectedCharacters` exception. That seems reasonable. Unfortunately, `commentjson.py:205` will then catch this as a generic `Exception` and translate it into a `JSONLibraryException(e)`. This is bad because it breaks API-compatibility with the Python `json` library, which would just raise a `ValueError`

**Comment by vaidik** [comment]
Not fixing this directly. Instead of that support for trailing commas is being added to expand use-cases for commentjson.
