### ISSUE TITLE
Test latest Lark changes to reconstructor

### ISSUE THREAD

**Issue by erezsh** [vaidik/commentjson#45]
We accepted a pull-request to Lark for the reconstructor that makes it faster, and better at handling ambiguity. Everything should still work as before, and the speed should increase.

But, the change is big enough that we might have missed something.

Any chance you could check-out the latest `lark-parser:master` and let me know if there's a problem with it? I don't plan to make a release in the next few weeks, but I bet you'd want to vet it before I do.

(This is the commit, if you're interested: https://github.com/lark-parser/lark/commit/f84a964463fed83256bff617992115f7733dd81f)

I'm also curious if you notice an improvement in performance, but that's less crucial.

**Comment by vaidik** [comment]
Thanks for following up on this. I will do this over the weekend and let you know about my test results.

**Comment by vaidik** [comment]
I tested this out locally with your commit. I don't see any problem. Should be good for release from my side.

If you want, I can test it again right before you are making the release.
